# version number
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"  
    environment:
      - VITE_SERVER_HOST=true       
    depends_on:
      - db
  backend:
    env_file: ./backend/.env
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"   
    depends_on:
      - db
  db:
    env_file: .env      
    volumes:
      - merndb:/data/db
    image: mongo:latest
    ports:
      - "27017:27017" 
volumes:
   merndb:
